### ISSUE TITLE
Add a @Reader macro annotation

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#1]
Creating the implicit `reader` definitions for a given `ApplicationConfig` class is repetitive and can probably provided by creating a `@Reader` macro annotation.

Instead of writing 
```scala
case class ApplicationConfig(
  threadPoolConfig: ThreadPoolConfig,
  serverConfig: ServerConfig
)

object ApplicationConfig {
   implicit def threadPoolConfigReader: Reader[ApplicationConfig, ThreadPoolConfig] = 
      Reader(_.threadPoolConfig)

   implicit def serverConfigReader: Reader[ApplicationConfig, ServerConfig] = 
      Reader(_.serverConfig)
}
```
There could be an annotation generating the implicit definitions automatically:
```scala
@Reader
case class ApplicationConfig(
  threadPoolConfig: ThreadPoolConfig,
  serverConfig: ServerConfig
)
```

Note that all the attributes of a config must have a different type. Otherwise we will generate conflicting `Reader` instances. There should be a compiler error in that case.

**Comment by jcranky** [comment]
So this is now to be closed?

**Comment by etorreborre** [comment]
Yes.
