### ISSUE TITLE
Report the success of `replace`

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#108]
At the moment the `replace` method returns the application graph with no indication of the success of the replacement. We could add a method `replaceAtLeastOnce` which would return `Option[Application]` with `None` as a result if nothing was replaced.

**Comment by danielkarch** [comment]
Can this be as simple as 
```
val rewritten = original.replace(a)
if (rewritten == original) 
  None
else 
  Some(rewritten)
```
? Not the most efficient way of doing it, but it should work.

**Comment by etorreborre** [comment]
I think there's a `RewriterCallback` inside Kiama which we could use to avoid a deep `==`.

**Comment by danielkarch** [comment]
I had a look. It's called `CallbackRewriter` and the callback is 

``` 
def rewriting[T](oldTerm : T, newTerm : T) : T
```

So any kind of notification of success would need to be implemented via a side-effect. It's a bit ugly.

**Comment by jcranky** [comment]
So perhaps the `==` comparison can work instead? I would love to see something that allow us to have message saying `replace X by Y`, as specific as possible - that could make `replace` less dangerous.

**Comment by etorreborre** [comment]
@danielkarch I don't think I mind that much if this is well encapsulated for the user. Because the win is big.

**Comment by danielkarch** [comment]
Okay, I will have a go at it.
