### ISSUE TITLE
Reduce genericReader boilerplate

### ISSUE THREAD

**Issue by shanethehat** [zalando/grafter#11]
In a similar vein to the `@readers` annotation, it would be nice to provide a way to remove the fairly common genericReader boilerplate:

```scala
object Foo {
  implicit def reader: Reader[ApplicationConfig, Foo] = genericReader
}
```

Would another macro annotation like `@genericReader` be a suitable solution?

**Comment by etorreborre** [comment]
Yes simply `@reader` would be a good idea.

**Comment by shanethehat** [comment]
I've made a start on trying to implement it, but I'm a bit of a macro novice so this might not be great on the first attempt. Currently struggling with how to pass the Reader's `A` type parameter through the macro.
