### ISSUE TITLE
Support typed components with type bounds

### ISSUE THREAD

**Issue by jcranky** [zalando/grafter#115]
Like:

```scala
case class ApplicationConfig[E <: Env]
```

**Comment by etorreborre** [comment]
I am not sure this is worth the added complexity. What can we do with this bound that we can not do otherwise?

**Comment by jcranky** [comment]
Allow the right hierarchy of classes to de used. Not a huge thing, I would say it is a nice-to-have, not a must.

**Comment by etorreborre** [comment]
I am going to close this for now until we find a use case showing that this really prevents some class of errors (and also when we know how to implement it - will need more macro playing time for this :-)).

**Comment by jcranky** [comment]
"it is not a bug, it is a feature" :P
