### ISSUE TITLE
Configuration with type parameters

### ISSUE THREAD

**Issue by aeons** [zalando/grafter#118]
I have some external components, that I can't really create through grafter's functionality (they are created by an `fs2.Stream`).

I had the idea to add some kind of context case class to my configuration, with the "external" dependencies. However, doing it this way requires a type parameter in my config class (`case class Config[F[_]](...)`), which gives this error:

```
[error] ...: A1 takes no type parameters, expected: one
[error] @readers
```

Should I just not do it this way? If not, is there a way to do something like this?

**Comment by etorreborre** [comment]
This is not implemented but you can attempt a PR along the lines of https://github.com/zalando/grafter/blob/4a7a782a76f5738f3cb086510682606f19302cee/macros/src/main/scala/org/zalando/grafter/macros/DefaultReaderMacro.scala#L23
