### ISSUE TITLE
bug in Quick Start docs at https://zalando.github.io/grafter

### ISSUE THREAD

**Issue by karlroberts** [zalando/grafter#125]
I would have crated a pull request but couldn't find these docs in this git repo. Presume they are off in a different place, but the link is referenced from here and zalando does say you are the maintainer :-)

Anyway, the bug is that the main() method in the quick start example is not wrapped in an Object.

Cheers

Karl

**Comment by etorreborre** [comment]
You're right Karl! Now I have 2 solutions, either I remember how to redeploy the doc after fixing it, or I wait until Scala 3 where this will become valid :-)

**Comment by etorreborre** [comment]
This is [fixed now](https://etorreborre.github.io/grafter/). Note that the project is now maintained in my own account: https://github.com/etorreborre/grafter.

**Comment by karlroberts** [comment]
Thanks Eric. I'll head over to your account :-)
