### ISSUE TITLE
Intellij plugin

### ISSUE THREAD

**Issue by shanethehat** [zalando/grafter#17]
Intellij does not understand the macros used by Grafter, because it does not compile Scala code to perform its syntax checks. This is an issue because Intellij will fail to detect required imports correctly, and may clean up imports it believes to be unused which will break an application.

This is probably a band-aid rather than a properly viable solution, but I've created a basic Intellij plugin to recreate the work that the macros are doing within the Intellij AST. I'm finding it useful, but feedback would be appreciated.

https://plugins.jetbrains.com/idea/plugin/9387-grafter-macro-support
https://github.com/shanethehat/grafter-intellij-plugin

**Comment by etorreborre** [comment]
Hi Shane, thanks for this plugin! I haven't been using the annotations much yet but I am going to try your plugin and will let you know.

**Comment by joan38** [comment]
Instead of doing a plugin for Idea it would be better to switch from the deprecated macros to scala.meta.
Idea supports natively Scala.meta and anyway we will have to switch one day or another.

**Comment by shanethehat** [comment]
For sure there should be meta support. I suspect this will help with the compilation time issues in https://github.com/zalando/grafter/issues/20. It's something I was hoping to look into when I next have some free time.

I guess there's also the question of what kind of legacy version support this library wants to offer as to whether Macro support sticks around.

**Comment by joan38** [comment]
What mean is that it would be a wast of time to code a plugin for Idea instead of Scala.meta which is supposed to offer the cross scala version support.

**Comment by shanethehat** [comment]
Sorry, for some reason I thought it was 2.12+. I'll have to find some time to look into it properly.

**Comment by joan38** [comment]
Scala.meta's scala versions: https://github.com/scalameta/scalameta/blob/master/build.sbt#L8
Grafter's scala versions: https://github.com/zalando/grafter/blob/master/build.sbt#L52

Sounds like it should work :)
Thanks @shanethehat for your help!

**Comment by etorreborre** [comment]
@joan38 this looks like the right direction, I might have a go at it if I find the time.

**Comment by shanethehat** [comment]
I'm not sure that Meta is quite at the point that it can be used for this. Its tokenizing seems solid, but the macro support depends on a new Paradise plugin that currently only seems to support 2.11. A 3.0.0 release looks like it's not far off, but without that I don't think it can be used for annotation based macros.

**Comment by dvic** [comment]
I'm not too familiar with the scalameta paradise plugin, but release `3.0.0-M8` is now built for Scala 2.11.11 and 2.12.2. Has scalameta now become a viable solution? (including annotation based macros)?

**Comment by jcranky** [comment]
Just as a note, we cannot use scala 2.12.2 yet - see https://github.com/zalando/grafter/issues/63

**Comment by etorreborre** [comment]
@dvic yes scalameta might be a solution now but we don't have much bandwidth to try it out at the moment.

**Comment by etorreborre** [comment]
I am going to close this for now. The solution is not scalameta which brings its own set of problems (https://github.com/scalameta/scalameta/issues/1051 for example). Let's revisit this when we can do #96
