### ISSUE TITLE
Publish the sources

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#18]
The current grafter sources jar is [empty in Maven central](http://central.maven.org/maven2/org/zalando/grafter_2.11/1.3.2).

**Comment by etorreborre** [comment]
@13h3r the sources are now available for version [`1.3.3`](https://oss.sonatype.org/content/repositories/releases/org/zalando/grafter_2.12/1.3.3).

**Comment by 13h3r** [comment]
Thanks! It works now
