### ISSUE TITLE
Reduce compilation times with the @reader annotation

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#20]
@shanethehat I just did a test on our project and replaced `genericReader` definitions for 8 components with `@reader` annotations. Result: `+30s` for our build time (`126s` vs `96s`).

Do you have any idea on how to improve that?

**Comment by shanethehat** [comment]
Wow, that's pretty significant. I'll see if can figure something out.

**Comment by etorreborre** [comment]
I also tested the `@readers` annotation on our `ApplicationConfig` and replaced it with 14 implicit definitions. I observed a further drop of 10 seconds.

**Comment by shanethehat** [comment]
My (admittedly simple) test application doesn't seem to have such dramatic differences. Which versions of Scala/SBT are you using?

**Comment by jcranky** [comment]
Scala 2.11.9 / Sbt 0.13.13

**Comment by etorreborre** [comment]
It looks like the `@readers` annotation makes compilation more performant but having `@reader` annotation on components degrades the compilation times. The likely explanation is that macro expansion is costly but it is also possible that unnecessary work is done. 

The next step would be to compare the AST generated with the `@reader` macro and with the manual `implicit def reader` definition.

**Comment by shanethehat** [comment]
The AST for the annotated case class in `ReaderMacroTest` prints as 

```scala
List(case class C extends scala.Product with scala.Serializable {
  def <init>() = {
    super.<init>();
    ()
  }
}, object C extends scala.AnyRef {
  def <init>() = {
    super.<init>();
    ()
  };
  import org.zalando.grafter.GenericReader._;
  implicit def reader: cats.data.Reader[ApplicationConfig, C] = genericReader
})
```

**Comment by etorreborre** [comment]
No difference really... Maybe the time difference just come from *producing* the AST from inside the macro, not compiling it afterwards.

**Comment by shanethehat** [comment]
The main thing that's different between the two macros is that the Reader macro has to figure out the config class name from the type parameter of the annotation. I'm trying to see if that takes an unusually long time. It does contain a couple of loops, but they were intended to break early.

**Comment by jcranky** [comment]
@etorreborre If I understood our last discussion in the topic, this is not an issue anymore, right?

**Comment by etorreborre** [comment]
Right this can be closed now.
