### ISSUE TITLE
Replace a service before starting the application

### ISSUE THREAD

**Issue by joan38** [zalando/grafter#24]
When I do:
```
val application: Application =
  GenericReader[ApplicationConfig, Application].
    run(testConfiguration).
    replace[Database](mockDb)
```
This actually instantiate the default Database and then replace it by the mock.

This behaviour is exactly what we don't want when mocking because in my case it throw an exception as it checks the validity of some credentials.

**Comment by shanethehat** [comment]
The pattern for the components is that they should be completely lazy to prevent this kind of thing from happening. If you have some validation that you need to run at startup you could use the `Start` trait and fail if the validation fails.


```scala
case class PostgresDatabase(dbConfig: DbConfig) extends Start with Database {
  def start: Eval[StartResult] =
    StartResult.eval("postgres") {
      // use dbConfig.url to initialize
    }
}
```

**Comment by joan38** [comment]
Just realised that, I'm now watching again this video:
https://skillsmatter.com/skillscasts/8981-practical-eff-monad-for-microservices

Thanks @shanethehat
