### ISSUE TITLE
Display a graph of components

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#26]
It would be very useful to be able to display a graph of components as a dot file, showing dependencies and where singletons have been made, with various options to remove unnecessary information (display dependencies only for example).

**Comment by jcranky** [comment]
dot file?

**Comment by etorreborre** [comment]
Yes, for example.

**Comment by jcranky** [comment]
I'm not sure I know what a `dot file` is :|

**Comment by etorreborre** [comment]
Sorry :-). This is [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)).

**Comment by jcranky** [comment]
@etorreborre thanks :D

**Comment by etorreborre** [comment]
Done.
