### ISSUE TITLE
scala.js support?

### ISSUE THREAD

**Issue by KimStebel** [zalando/grafter#79]
Has anyone tried compiling grafter with scala.js? Does grafter use anything JVM-specific?

**Comment by etorreborre** [comment]
This might be a bit hard to do because we currently rely on Kiama which doesn't have yet a [Scala.js version](https://github.com/joaoraf/kiama/issues/64).

**Comment by etorreborre** [comment]
I am closing this for now because there's no obvious answer until  Kiama is ported to Scala.js.
