### ISSUE TITLE
readers annotation generating reader for self

### ISSUE THREAD

**Issue by pjan** [zalando/grafter#80]
The following bit of code (excluded all imports and ceremony for brevity) fails to compile. (The usecase might be specific, but it would be great if it would also just work)

```scala
@readers
case class ApplicationConfig(
  dbConfig: DbConfig
)

@reader[ApplicationConfig]
case class Foo(config: ApplicationConfig, db: DB)
```

It fails because there's no implicit reader instance (`Reader[ApplicationConfig, ApplicationConfig]`) to be found.

It would be resolved if the `@readers` annotation would also generate the following

```scala
object ApplicationConfig {
  implicit val reader: Reader[ApplicationConfig, ApplicationConfig] =
    Reader.apply(identity)
}
```

**Comment by pjan** [comment]
@etorreborre you beat me to it. I was opening a PR for it, but when looking for the issue, I just saw you already addressed it. 🚀

**Comment by etorreborre** [comment]
:-). Now I'm just waiting a bit to see if I can get the final version of `Kiama 2.1.0` before I publish a new grafter version. But I can publish an interim version if you need it now.

**Comment by pjan** [comment]
We can temporarily live with the additional 4 LoCs. We opened an issue to remove these once an updated version is released, so we can wait it out.

btw: our latest service uses both `grafter` and `eff` extensively (in combination with `cats`, `pureconfig` & `tagless final`) and the modularity this all offers us is nothing short from amazing.

**Comment by etorreborre** [comment]
Very nice! A blog post coming up :-) ?
