### ISSUE TITLE
Visualize components attributes 

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#94]
It would be nice to be able to display attributes when [producing an application graph](https://github.com/zalando/grafter/blob/master/doc/inspect-app-graph.md).

Typically we can show as attributes any case class member which is not a dependency itself. For examples "configuration" case classes members fall in that category:
```
@reader
case class HttpServer(config: HttpServerConfig)

case class HttpServerConfig(host: String, port: Int)
```
Then we should see `host` and `port` printed in the `.dot` graph for the `HttpServer`.

**Comment by danielkarch** [comment]
What kind of attributes are you thinking of?
