### ISSUE TITLE
Migrate to the new scala macros

### ISSUE THREAD

**Issue by etorreborre** [zalando/grafter#96]
The current macro annotations are using Scalameta but they are showing an [issue](https://github.com/scalameta/scalameta/issues/1051) which might not be solved so soon.

The new [scalamacros](https://github.com/scalamacros/scalamacros) could solve this problem. We need to test on one annotation if:

 - scalamacros has enough features already to support the grafter use case
 - the issue in Scalameta is fixed

**Comment by etorreborre** [comment]
Help is needed on the `scalamacros` project! Currently the methods supporting `grafter`s use case are not implemented.

**Comment by taojang** [comment]
the `scalamacros` project seems to be archived already :(

**Comment by etorreborre** [comment]
Yes let's close this and wait for Scala 3 :-)
