### ISSUE TITLE
Can we mention grafter in cats' README? 

### ISSUE THREAD

**Issue by kailuowang** [zalando/grafter#98]
in the list of cats ecosystem projects.

**Comment by jcranky** [comment]
I think it is ok. @LappleApple do we have any official policy regarding this?

**Comment by etorreborre** [comment]
I would be happy to, it's using cats and `Reader` instances for dependency injection so it makes sense to me.

**Comment by etorreborre** [comment]
I created a [PR](https://github.com/typelevel/cats/pull/1846) but to do things well we probably need to finish #71 which is about having compiler-checked documentation.

**Comment by etorreborre** [comment]
Done, the compiler-checked documentation is not necessary to be mentioned in cats' readme.
